const  actionTypes={
    EMAILSIGNINSTART:"EMAILSIGNINSTART",
    GOOGLESIGNINSTART:"GOOGLESIGNINSTART",
    SIGNINSUCCESS:"SIGNINSUCCESS",
   
   SIGNINFAILURE:"SIGNINFAILURE",
   CHECKUSERSEESION:"CHECKUSERSEESION",
   SIGNOUTSTART:"SIGNOUTSTART",
   SIGNOUTSUCCESS:"SIGNOUTSUCCESS",
   SIGNOUTFAILURE:"SIGNOUTFAILURE",
   SIGNUPSTART:"SIGNUPSTART",
   SIGNUPSUCCESS:"SIGNUPSUCCESS",
   SIGNUPFAILURE:"SIGNUPFAILURE",
    
    
}
export default actionTypes;